#!/bin/bash

# Store UUID and task in ~/.stack/completed
echo "`date +%s` `head -n 1 ~/.stack/stack`" >> ~/.stack/completed

# Pop the UUID and task from ~/.stack/stack
echo "Pop'd `head -n 1 ~/.stack/stack | cut -c 34- ` "
sed -i -e "1d" ~/.stack/stack
