#!/bin/bash

# Add UUID and task to ~/.stack/stack
echo "$(md5 -qs "$1 `date`" ) $1" | cat - ~/.stack/stack > ~/.stack/tmp
mv ~/.stack/tmp ~/.stack/stack

# Add UUID, timestamp and task to ~/.stack/opened
echo "`date +%s` $(md5 -qs "$1 `date`" ) $1" | cat - ~/.stack/opened > ~/.stack/tmp
mv ~/.stack/tmp ~/.stack/opened
